# Generated by Django 2.2.7 on 2019-11-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191117_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('load', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='LOW', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Node'),
        ),
    ]
