# Generated by Django 2.2.7 on 2019-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191117_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='colname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
