# Generated by Django 2.2.7 on 2019-11-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job'),
        ),
    ]
