# Generated by Django 2.2.7 on 2019-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191120_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_val',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='max_val',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='min_val',
            field=models.FloatField(null=True),
        ),
    ]
